### ISSUE TITLE
This github repository is not searchable, intuitive, or easy to use

### ISSUE THREAD

**Issue by jack-valko** [zabbix/community-templates#23]
Unlike share.zabbix.com, this repo is not searchable.  This is an important feature on share.zabbix.com that allows users to find templates for their devices.  This repo is not easy to use if you want to add a template, not all of us are developers.  The layout of template name/version/release is cumbersome and difficult.

Suggestions:
- ditch this idea and improve zabbix share instead
- index this github repo on search engines
- enable the github wiki with a searchable index

**Comment by mtxadmin** [comment]
Zabbix share was a total mess. I tried to add my templates there, and without any response. Here all people have a chance to add a template in a normal way.

But index and wiki are needed, yes.

**Comment by jack-valko** [comment]
“In a normal way” doesn’t compute. Normal if you use git and understand branching and PR. Not normal if you spend most of your time on Reddit. 

Guidance will help.

**Comment by mtxadmin** [comment]
I disagree. On Github here is a very clear and intuitive web-interface.

**Comment by monotok** [comment]
I would say git is the right place to host this but I do miss comments on each template. You could tell if it was worth downloading and trying.

**Comment by jack-valko** [comment]
@mtxadmin I disagree with your disagreement.  I'm not arguing the github web interface isn't clear or intuitive for doing github stuff.  It is unintuitive or incompatible for really important use cases like adding a template, searching for a template, reading comments (those will never exist), and ranking templates (those will never exist).  It's a major feature downgrade from what was available on zabbix share.

Speaking as a zabbix community developer, if my potential users can't find my stuff then what am I still doing here?

**Comment by hlovdal** [comment]
What could be done is to add a (formal) meta information text file containing summary, description and listing details to the top level of directory of each template (think [lsm](https://en.wikipedia.org/wiki/Linux_Software_Map) but much more modern).

This could be in a readme markdown (with some content requirement) so that it that can be rendered directly or a readme file could be automatically generated from the template meta information file (which would improve browsing this repository by itself).

With this one could simply aggregate all those and feed into a frontend system (which could eventually be made as sofisticated as share.zabbix.com).

**Comment by nod0n** [comment]
I do agree that share.zabbix.com does have some nice features I miss here. I'm used to git and grep, but having votes, download numbers, versions, comments is very useful!
