### ISSUE TITLE
template_synology_diskstation Disk size/usage/percentage incorrect

### ISSUE THREAD

**Issue by matttb** [zabbix/community-templates#72]
HI
This script incorrectly pulls the correct sizes from my Synology NAS. On a 60TB disk named /volume1it only reports 7TB. However if I SNMPWALK using the OID from Synology for disk info, I get the correct raw values:

snmpwalk -v2c -c public *.*.*.*.* .1.3.6.1.4.1.6574.3
iso.3.6.1.4.1.6574.3.1.1.1.0 = INTEGER: 0
iso.3.6.1.4.1.6574.3.1.1.2.0 = STRING: "Volume 1"
iso.3.6.1.4.1.6574.3.1.1.3.0 = INTEGER: 1
iso.3.6.1.4.1.6574.3.1.1.4.0 = Counter64: 2423850156032
iso.3.6.1.4.1.6574.3.1.1.5.0 = Counter64: 65697681559552

The script seems to be going a long way round when the values are presented on this ID in Bytes. Could you please correct this?

**Comment by k008** [comment]
`return (parseInt(value) * parseInt("{#IFUNIT}"));`

![изображение](https://user-images.githubusercontent.com/8766589/177171514-fa2f1f85-2eb3-409c-a47f-66ac3811ce1b.png)

**Comment by johnhoogeveen** [comment]
Does this work correctly?
When I check my internal volume the mismatch is a factor 4 so the multiplier should be 16384 instead of 4094, while my usb disk attached to the synology is wrong by a factor 2 requiring the multiplier to be 8192 instead of 4096
By using  hrStorageAllocationUnits.xx (.1.3.6.1.2.1.25.2.3.1.4) in the calculation you can use the correct blocksize (now the default is 4996) but that can vary.
In the SNMP dump below, .56 is my internal storage and .63 is my external usb drive. (.64 is the docker volume which is running on volume1 being .56

Name/OID: hrStorageAllocationUnits.1; Value (Integer): 1024
Name/OID: hrStorageAllocationUnits.3; Value (Integer): 1024
Name/OID: hrStorageAllocationUnits.6; Value (Integer): 1024
Name/OID: hrStorageAllocationUnits.7; Value (Integer): 1024
Name/OID: hrStorageAllocationUnits.8; Value (Integer): 1024
Name/OID: hrStorageAllocationUnits.10; Value (Integer): 1024
Name/OID: hrStorageAllocationUnits.31; Value (Integer): 4096
Name/OID: hrStorageAllocationUnits.36; Value (Integer): 4096
Name/OID: hrStorageAllocationUnits.38; Value (Integer): 4096
Name/OID: hrStorageAllocationUnits.39; Value (Integer): 4096
Name/OID: hrStorageAllocationUnits.51; Value (Integer): 4096
Name/OID: hrStorageAllocationUnits.56; Value (Integer): 16384
Name/OID: hrStorageAllocationUnits.58; Value (Integer): 4096
Name/OID: hrStorageAllocationUnits.59; Value (Integer): 4096
Name/OID: hrStorageAllocationUnits.60; Value (Integer): 4096
Name/OID: hrStorageAllocationUnits.63; Value (Integer): 8192
Name/OID: hrStorageAllocationUnits.64; Value (Integer): 16384
Name/OID: hrStorageSize.1; Value (Integer): 6095880
Name/OID: hrStorageSize.3; Value (Integer): 11850676
Name/OID: hrStorageSize.6; Value (Integer): 6095880
Name/OID: hrStorageSize.7; Value (Integer): 4705908
Name/OID: hrStorageSize.8; Value (Integer): 39724
Name/OID: hrStorageSize.10; Value (Integer): 5754796
Name/OID: hrStorageSize.31; Value (Integer): 596382
Name/OID: hrStorageSize.36; Value (Integer): 761985
Name/OID: hrStorageSize.38; Value (Integer): 761985
Name/OID: hrStorageSize.39; Value (Integer): 761985
Name/OID: hrStorageSize.51; Value (Integer): 761985
Name/OID: hrStorageSize.56; Value (Integer): 1170658963
Name/OID: hrStorageSize.58; Value (Integer): 5120
Name/OID: hrStorageSize.59; Value (Integer): 5120
Name/OID: hrStorageSize.60; Value (Integer): 5120
Name/OID: hrStorageSize.63; Value (Integer): 1695440003
Name/OID: hrStorageSize.64; Value (Integer): 1170658963
Name/OID: hrStorageUsed.1; Value (Integer): 5957972
Name/OID: hrStorageUsed.3; Value (Integer): 6572860
Name/OID: hrStorageUsed.6; Value (Integer): 246668
Name/OID: hrStorageUsed.7; Value (Integer): 4705908
Name/OID: hrStorageUsed.8; Value (Integer): 39724
Name/OID: hrStorageUsed.10; Value (Integer): 614888
Name/OID: hrStorageUsed.31; Value (Integer): 536746
Name/OID: hrStorageUsed.36; Value (Integer): 46
Name/OID: hrStorageUsed.38; Value (Integer): 6748
Name/OID: hrStorageUsed.39; Value (Integer): 0
Name/OID: hrStorageUsed.51; Value (Integer): 360
Name/OID: hrStorageUsed.56; Value (Integer): 862803697
Name/OID: hrStorageUsed.58; Value (Integer): 0
Name/OID: hrStorageUsed.59; Value (Integer): 0
Name/OID: hrStorageUsed.60; Value (Integer): 0
Name/OID: hrStorageUsed.63; Value (Integer): 933325362
Name/OID: hrStorageUsed.64; Value (Integer): 862803697

**Comment by igorbach** [comment]
@k008, feel free to make a pull request with a fix provided
